FROM kubelilin/nginx_container:v1.23.1

USER 0

# Modify timezone
ENV TZ=Asia/Shanghai

RUN apt-get update; \
    apt-get install -y \
        vim \
        curl \
        ca-certificates && \
        rm -rf /var/lib/apt/lists/*


# aliyun mirror
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak; \
    sed -i 's http://.*.debian.org http://mirrors.aliyun.com g' /etc/apt/sources.list
